conditioning:
  method: ps
  params:
    scale: 13  # \zeta^{'} in dps paper

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 128, 128]
    scale_factor: 2
  
  noise: 
    name: gaussian
    sigma: 0.02
